### ISSUE TITLE
List all estimator parameters for grid search compatability

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/sknnr#74]
I was testing out `GridSearchCV` with `GNNRegressor` and realized that we have an issue with our `__init__` signatures for `GNNRegressor` and `MSNRegressor`. Currently those only explicitly accept `n_components` and take all other parameters (like `n_neighbors`) via `**kwargs`, but grid searching requires all searchable parameters to be explicitly stated to satisfy this check:

https://github.com/scikit-learn/scikit-learn/blob/24b581bce88598d92954182fab53e760cf92e6bd/sklearn/base.py#L277C13-L282C18

I think this should be an easy fix of just explicitly adding all the `KNeighborsRegressor.__init__` parameters, which should also make for a nicer docstring and better Intellisense. We should probably also add a quick test for grid search functionality while we're at it.

`EuclideanKNNRegressor` and `MalahanobisKNNRegressor` should be okay because they don't override their `__init__` methods.

**Comment by grovduck** [comment]
Good find and that sounds like a good path forward!  I like the idea of getting a `GridSearchCV` test in there as well!
