### ISSUE TITLE
scikit-learn 1.6 compatibility

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/sknnr#78]
There's a release candidate `scikit-learn==1.6.0rc1` with some breaking changes that are coming with the next release. Most of our tests are failing because we rely on `base.BaseEstimator._validate_data` which is now public via `utils.validation.validate_data`. That's an easy fix, but it's possible those failures are hiding some trickier issues with the [updated tag system](https://scikit-learn.org/1.6/developers/develop.html#estimator-tags). Sounds like there's also [ongoing work](https://bsky.app/profile/ogrisel.bsky.social/post/3lbkhz7ko722z) to simplify the tag system transition before the final release.

Changelog: https://scikit-learn.org/1.6/whats_new/v1.6.html#version-1-6-0

**Comment by grovduck** [comment]
Thanks for tracking this, @aazuspan
